export const ASSETS = [
    {
        symbol: "XAUc",
        name: "Comdex Gold",
        price: "65.78",
        changeValue: "0.42",
        changePercent: "0.64%",
        isPositive: true,
        avatar: "G",
        volume: "1,240,500",
        color: "#FFD700",
        description: "Comdex Gold (XAUc) provides exposure to the spot price of 1 gram of physical gold. Each token represents ownership of gold held in secure, audited vaults.",
        category: "Metal",
        address: "0xGOLD...XAUc",
        underlying: "Gold Spot (1g)",
        chains: ["BNB Chain"]
    },
    {
        symbol: "XAGc",
        name: "Comdex Silver",
        price: "0.75",
        changeValue: "0.01",
        changePercent: "1.32%",
        isPositive: false,
        avatar: "S",
        volume: "850,200",
        color: "#C0C0C0",
        description: "Comdex Silver (XAGc) offers tokenized exposure to 1 gram of physical silver, allowing investors to trade silver with the liquidity of a digital asset.",
        category: "Metal",
        address: "0xSLVR...XAGc",
        underlying: "Silver Spot (1g)",
        chains: ["BNB Chain"]
    },
    {
        symbol: "XPDc",
        name: "Comdex Palladium",
        price: "30.55",
        changeValue: "0.45",
        changePercent: "1.50%",
        isPositive: true,
        avatar: "P",
        volume: "12,400",
        color: "#5D9B76",
        description: "XPDc provides direct exposure to 1 gram of Palladium, tracking the performance of one of the world's most valuable industrial metals.",
        category: "Metal",
        address: "0xPALL...XPDc",
        underlying: "Palladium Spot (1g)",
        chains: ["BNB Chain"]
    },
    {
        symbol: "XPTc",
        name: "Comdex Platinum",
        price: "29.42",
        changeValue: "0.18",
        changePercent: "0.80%",
        isPositive: false,
        avatar: "P",
        volume: "8,800",
        color: "#4A7EBB",
        description: "XPTc tokens represent ownership of 1 gram of physical platinum, offering an easy way to diversify into precious metals via on-chain settlement.",
        category: "Metal",
        address: "0xPLAT...XPTc",
        underlying: "Platinum Spot (1g)",
        chains: ["BNB Chain"]
    },
    {
        symbol: "BRNc",
        name: "Comdex Brent Oil",
        price: "78.45",
        changeValue: "0.67",
        changePercent: "0.85%",
        isPositive: false,
        avatar: "O",
        volume: "450,000",
        color: "#216477",
        description: "Comdex Brent Oil (BRNc) tracks the price of Brent Crude oil, enabling traders to get exposure to energy markets without derivative contracts.",
        category: "Commodity",
        address: "0xOIL...BRNc",
        underlying: "Brent Crude",
        chains: ["BNB Chain"]
    },
    {
        symbol: "XCUc",
        name: "Comdex Copper",
        price: "0.02",
        changeValue: "0.001",
        changePercent: "1.15%",
        isPositive: true,
        avatar: "C",
        volume: "2,100,500",
        color: "#d35400",
        description: "XCUc provides exposure to industrial grade copper prices (per 1 gram), widely used as an indicator for global economic health.",
        category: "Metal",
        address: "0xCOPP...XCUc",
        underlying: "Copper (1g)",
        chains: ["BNB Chain"]
    },
    {
        symbol: "CUSD",
        name: "Comdex USD",
        price: "1.00",
        changeValue: "0.00",
        changePercent: "0.00%",
        isPositive: true,
        avatar: "C",
        volume: "5,000,000",
        color: "#8B5CF6",
        description: "CUSD is the base stablecoin of the Comdex ecosystem, pegged 1:1 to the US Dollar and backed by diversified cash and cash equivalents.",
        category: "Stable",
        address: "0x99CUSD...COMDX",
        underlying: "USD",
        chains: ["BNB Chain"]
    },
    {
        symbol: "USDT",
        name: "Tether USD",
        price: "1.00",
        changeValue: "0.00",
        changePercent: "0.00%",
        isPositive: true,
        avatar: "T",
        volume: "15,000,000",
        color: "#50af95",
        description: "Tether (USDT) is a stablecoin pegged to the US Dollar, widely used across the crypto ecosystem for liquidity and stability.",
        category: "Stable",
        address: "0xdAC1...USDT",
        underlying: "USD",
        chains: ["BNB Chain"]
    },
];
